<?php
const C_REST_CLIENT_ID = 'local.64959fb73ec6a8.15471314';//Application ID
const C_REST_CLIENT_SECRET = 'T6j1NjJbfRroIMkjsVYgMq1xz9jzt86f1M32A6o74KZ0yNuQYB';//Application key
// or
//define('C_REST_WEB_HOOK_URL','https://rest-api.bitrix24.com/rest/1/doutwqkjxgc3mgc1/');//url on creat Webhook

//define('C_REST_CURRENT_ENCODING','windows-1251');
//define('C_REST_IGNORE_SSL',true);//turn off validate ssl by curl
//define('C_REST_LOG_TYPE_DUMP',true); //logs save var_export for viewing convenience
const C_REST_BLOCK_LOG = true;//turn off default logs
//define('C_REST_LOGS_DIR', __DIR__ .'/logs/'); //directory path to save the log
define('SERVER_PATH', $_REQUEST['DOMAIN'], true);
const ABSOLUTE_DIR = '/var/www/btx24conn/';
const SERVER_HOST = '45.147.177.196';
const TABLES_LIST = array("db_groups", "db_list", "db_deal_category", "db_office", "db_users",
    "db_contacts", "db_tasks", "db_company", "db_deals", "db_leads",
    "db_calls", "db_invoice", "db_smart_process_type", "db_smart_process_category",
    "db_smart_process", "db_offers", "db_activity", "db_catalog", "db_catalog_type",
    "db_product", "db_comments", "db_work_time");
const TABLES_LIST_RUS = array(
    "db_groups" => "Группы",
    "db_list" => "Списки",
    "db_deal_category" => "Категории сделок",
    "db_office" => "Офисы",
    "db_users" => "Пользователи",
    "db_contacts" => "Контакты",
    "db_tasks" => "Задачи",
    "db_company" => "Компании",
    "db_deals" => "Сделки",
    "db_leads" => "Лиды",
    "db_calls" => "Звонки",
    "db_invoice" => "Счета",
    "db_smart_process_type" => "Типы умных процессов",
    "db_smart_process_category" => "Категории умных процессов",
    "db_smart_process" => "Умные процессы",
    "db_offers" => "Предложения",
    "db_activity" => "Активности",
    "db_catalog" => "Каталог",
    "db_catalog_type" => "Типы каталога",
    "db_product" => "Продукты",
    "db_comments" => "Комментарии",
    "db_work_time" => "Рабочее время"
);
const RESERVED_WORDS_SQL = array("SYSTEM", "ACCESSIBLE", "ADD", "ALL", "ALTER", "ANALYZE", "AND", "AS", "ASC",
    "ASENSITIVE", "BEFORE", "BETWEEN", "BIGINT", "BINARY", "BLOB", "BOTH", "BY", "CALL", "CASCADE", "CASE", "CHANGE", "CHAR",
    "CHARACTER", "CHECK", "COLLATE", "COLUMN", "CONDITION", "CONSTRAINT", "CONTINUE", "CONVERT", "CREATE", "CROSS", "CURRENT_DATE",
    "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER", "CURSOR", "DATABASE", "DATABASES", "DAY_HOUR", "DAY_MICROSECOND", "DAY_MINUTE",
    "DAY_SECOND", "DEC", "DECIMAL", "DECLARE", "DEFAULT", "DELAYED", "DELETE", "DESC", "DESCRIBE", "DETERMINISTIC", "DISTINCT", "DISTINCTROW",
    "DIV", "DOUBLE", "DROP", "DUAL", "EACH", "ELSE", "ELSEIF", "ENCLOSED", "ESCAPED", "EXISTS", "EXIT", "EXPLAIN", "false", "FETCH", "FLOAT",
    "FLOAT4", "FLOAT8", "FOR", "FORCE", "FOREIGN", "FROM", "FULLTEXT", "GOTO", "GRANT", "GROUP", "HAVING", "HIGH_PRIORITY", "HOUR_MICROSECOND",
    "HOUR_MINUTE", "HOUR_SECOND", "IF", "IGNORE", "IN", "INDEX", "INFILE", "INNER", "INOUT", "INSENSITIVE", "INSERT", "INT", "INT1", "INT2",
    "INT3", "INT4", "INT8", "INTEGER", "INTERVAL", "INTO", "IS", "ITERATE", "JOIN", "KEY", "KEYS", "KILL", "LEADING", "LEAVE", "LEFT", "LIKE",
    "LIMIT", "LINEAR", "LINES", "LOAD", "LOCALTIME", "LOCALTIMESTAMP", "LOCK", "LONG", "LONGBLOB", "LONGTEXT", "LOOP", "LOW_PRIORITY", "MASTER_BIND",
    "MASTER_SSL_VERIFY_SERVER_CERT", "MATCH", "MAXVALUE", "MEDIUMBLOB", "MEDIUMINT", "MEDIUMTEXT", "MIDDLEINT", "MINUTE_MICROSECOND", "MINUTE_SECOND",
    "MOD", "MODIFIES", "NATURAL", "NOT", "NO_WRITE_TO_BINLOG", "NULL", "NUMERIC", "ON", "OPTIMIZE", "OPTION", "OPTIONALLY", "OR", "ORDER", "OUT",
    "OUTER", "OUTFILE", "PARTITION", "PRECISION", "PRIMARY", "PROCEDURE", "PURGE", "RANGE", "READ", "READS", "READ_WRITE", "REAL", "REFERENCES",
    "REGEXP", "RELEASE", "RENAME", "REPEAT", "REPLACE", "REQUIRE", "RESTRICT", "RETURN", "REVOKE", "RIGHT", "RLIKE", "SCHEMA", "SCHEMAS",
    "SECOND_MICROSECOND", "SELECT", "SENSITIVE", "SEPARATOR", "SET", "SHOW", "SMALLINT", "SPATIAL", "SPECIFIC", "SQL", "SQLEXCEPTION", "SQLSTATE",
    "SQLWARNING", "SQL_BIG_RESULT", "SQL_CALC_FOUND_ROWS", "SQL_SMALL_RESULT", "SSL", "STARTING", "STRAIGHT_JOIN", "TABLE", "TERMINATED", "THEN",
    "TINYBLOB", "TINYINT", "TINYTEXT", "TO", "TRAILING", "TRIGGER", "TRUE", "UNDO", "UNION", "UNIQUE", "UNLOCK", "UNSIGNED", "UPDATE", "USAGE",
    "USE", "USING", "UTC_DATE", "UTC_TIME", "UTC_TIMESTAMP", "VALUES", "VARBINARY", "VARCHAR", "VARCHARACTER", "VARYING", "WHEN", "WHERE", "WHILE",
    "WITH", "WRITE", "XOR", "YEAR_MONTH", "ZEROFILL", "0", "group");
const COLUMNS_NAMES_DICT = array(
    "db_groups" => array(
        "ID" => "Идентификатор группы",
        "NAME" => "Название группы",
        "DESCRIPTION" => "Описание группы",
        "DATE_CREATE" => "Дата создания группы",
        "OWNER_ID" => "Идентификатор создателя группы",
        "GROUP_TYPE" => "Название типа группы",
        "DATE_UPDATE" => "Дата последнего изменения группы",
        "ACTIVE" => "Флаг активности группы",
        "CLOSED" => "Флаг закрытости группы",
        "VISIBLE" => "Флаг приватности группы",
        "OPENED" => "Флаг видимости группы в поиске",
        "IMAGE_ID" => "Идентификатор изображения группы",
        "IMAGE_URL" => "Ссылка на изображение группы",
        "URL" => "URL группы",
        "PARENT_ID" => "Идентификатор родительской группы",
    ),
    "db_list" => array(
        "ID" => "Идентификатор статуса",
        "NAME" => "Название статуса",
        "SORT" => "Порядок сортировки статуса",
        "STATUS_ID" => "Код статуса",
        "ENTITY_ID" => "Код типа элемента CRM",
        "SYSTEM" => "Флаг системности статуса",
        "SEMANTICS" => "Семантика статуса",
        "COLOR" => "Цвет статуса",
        "EXTRA" => "Дополнительные параметры статуса",
        "CATEGORY_ID" => "Идентификатор категории, к которой относится статус",
        "IS_DEFAULT" => "Флаг, указывающий, что статус является стандартным для данной категории элементов",
        "SORTED_NAME" => "Название статуса в форме для сортировки",
    ),
    "db_deal_category" => array(
        "ID" => "Идентификатор категории",
        "NAME" => "Название категории",
        "SORT" => "Порядок сортировки категории",
        "ENTITY_ID" => "Код типа элемента CRM",
        "XML_ID" => "Внешний код категории",
        "STATUS_ID" => "Код статуса категории",
        "EXTRA" => "Дополнительные параметры категории",
        "IS_DEFAULT" => "Флаг, указывающий, что категория является стандартной для данного типа элементов",
    ),
    "db_office" => array(
        "ID" => "Идентификатор подразделения",
        "NAME" => "Название подразделения",
        "PARENT" => "Идентификатор родительского подразделения",
        "UF_HEAD" => "Идентификатор непосредственного руководителя подразделения",
        "UF_DEPARTMENT" => "Идентификаторы подразделений, в которые входит данное подразделение",
        "UF_PHONE_INNER" => "Внутренний телефон подразделения",
        "UF_FAX" => "Факс подразделения",
        "UF_EMAIL" => "E-mail подразделения",
        "UF_ADDRESS" => "Адрес подразделения",
        "UF_COORDINATES" => "Геокоординаты подразделения",
        "UF_METRO" => "Ближайшее метро к подразделению",
        "UF_PHOTO" => "Фотография подразделения",
        "UF_DESCRIPTION" => "Описание подразделения",
    ),
    "db_users" => array(
        "ID" => "Идентификатор пользователя",
        "NAME" => "Имя пользователя",
        "LAST_NAME" => "Фамилия пользователя",
        "SECOND_NAME" => "Отчество пользователя",
        "LOGIN" => "Логин пользователя",
        "EMAIL" => "E-mail пользователя",
        "PERSONAL_MOBILE" => "Номер мобильного телефона пользователя",
        "PERSONAL_PHONE" => "Номер телефона пользователя",
        "PERSONAL_CITY" => "Город проживания пользователя",
        "WORK_POSITION" => "Должность пользователя",
        "UF_DEPARTMENT" => "Идентификаторы подразделений, в которых состоит пользователь",
        "UF_PHONE_INNER" => "Внутренний телефон пользователя",
        "UF_SKYPE" => "Skype пользователя",
        "PERSONAL_PHOTO" => "Фотография пользователя",
        "WORK_COMPANY" => "Компания, в которой работает пользователь",
    ),
    "db_contacts" => array(
        "ID" => "Идентификатор контакта",
        "NAME" => "Имя контакта",
        "SECOND_NAME" => "Отчество контакта",
        "LAST_NAME" => "Фамилия контакта",
        "BIRTHDATE" => "Дата рождения контакта",
        "POST" => "Должность контакта",
        "ADDRESS" => "Адрес контакта",
        "COMMENTS" => "Комментарии к контакту",
        "TYPE_ID" => "Тип контакта",
        "SOURCE_ID" => "Источник контакта",
        "SOURCE_DESCRIPTION" => "Описание источника контакта",
        "ASSIGNED_BY_ID" => "Идентификатор ответственного за контакт",
        "CREATED_BY_ID" => "Идентификатор создателя контакта",
        "MODIFY_BY_ID" => "Идентификатор пользователя, последний раз изменившего контакт",
        "DATE_CREATE" => "Дата создания контакта",
        "DATE_MODIFY" => "Дата последнего изменения контакта",
        "COMPANY_TITLE" => "Название компании контакта",
        "PHOTO" => "Фотография контакта",
    ),
    "db_tasks" => array(
        "ID" => "Идентификатор задачи",
        "TITLE" => "Название задачи",
        "DESCRIPTION" => "Описание задачи",
        "CREATED_BY" => "Информация о пользователе, создавшем задачу",
        "RESPONSIBLE_ID" => "Идентификатор ответственного за задачу",
        "DEADLINE" => "Крайний срок выполнения задачи",
        "START_DATE_PLAN" => "Планируемая дата начала выполнения задачи",
        "END_DATE_PLAN" => "Планируемая дата окончания выполнения задачи",
        "DURATION_PLAN" => "Планируемая продолжительность выполнения задачи",
        "CREATED_DATE" => "Дата создания задачи",
        "CHANGED_DATE" => "Дата последнего изменения задачи",
        "STATUS" => "Статус задачи",
        "GROUP_ID" => "Идентификатор группы, к которой относится задача",
        "PRIORITY" => "Приоритет задачи",
        "MARK" => "Оценка задачи",
        "ALLOW_CHANGE_DEADLINE" => "Флаг, указывающий, разрешено ли изменять крайний срок задачи",
        "TASK_CONTROL" => "Флаг, указывающий, является ли задача контролируемой",
        "ADD_IN_REPORT" => "Флаг, указывающий, что задача включена в отчетность",
        "COMMENTS_COUNT" => "Количество комментариев к задаче",
        "NEW_COMMENTS_COUNT" => "Количество новых комментариев к задаче",
        "FAVORITE" => "Флаг, указывающий, добавлена ли задача в избранное",
        "TAGS" => "Теги, связанные с задачей",
        "ALLOW_TIME_TRACKING" => "Флаг, указывающий, разрешен ли учет времени для задачи",
        "TIME_SPENT_IN_LOGS" => "Общее время, затраченное на задачу",
        "GUID" => "Уникальный идентификатор задачи",
    ),
    "db_company" => array(
        "ID" => "Идентификатор компании",
        "TITLE" => "Название компании",
        "COMPANY_TYPE" => "Тип компании",
        "INDUSTRY" => "Отрасль компании",
        "REVENUE" => "Годовой доход компании",
        "CURRENCY_ID" => "Идентификатор валюты дохода компании",
        "EMPLOYEES" => "Количество сотрудников компании",
        "ADDRESS" => "Адрес компании",
        "ADDRESS_LEGAL" => "Юридический адрес компании",
        "BANKING_DETAILS" => "Банковские реквизиты компании",
        "COMMENTS" => "Комментарии к компании",
        "ASSIGNED_BY_ID" => "Идентификатор ответственного за компанию",
        "CREATED_BY_ID" => "Идентификатор создателя компании",
        "MODIFY_BY_ID" => "Идентификатор пользователя, последний раз изменившего компанию",
        "DATE_CREATE" => "Дата создания компании",
        "DATE_MODIFY" => "Дата последнего изменения компании",
        "OPENED" => "Флаг, указывающий, является ли компания открытой для всех сотрудников",
        "IS_MY_COMPANY" => "Флаг, указывающий, является ли компания текущей компанией пользователя",
        "ORIGINATOR_ID" => "Идентификатор источника компании",
        "ORIGIN_ID" => "Идентификатор компании в источнике",
        "ORIGIN_VERSION" => "Версия компании в источнике",
        "UF_" => "Значения пользовательских полей компании",
    ),
    "db_deals" => array(
        "ID" => "Идентификатор сделки",
        "TITLE" => "Название сделки",
        "TYPE_ID" => "Тип сделки",
        "STAGE_ID" => "Идентификатор стадии сделки",
        "PROBABILITY" => "Вероятность успешного закрытия сделки в процентах",
        "CURRENCY_ID" => "Идентификатор валюты сделки",
        "OPPORTUNITY" => "Сумма сделки",
        "ACCOUNT_CURRENCY_ID" => "Идентификатор валюты счета",
        "ACCOUNT_ID" => "Идентификатор счета, связанного с сделкой",
        "CLOSED" => "Флаг, указывающий, закрыта ли сделка",
        "CLOSE_DATE" => "Дата закрытия сделки",
        "COMMENTS" => "Комментарии к сделке",
        "BEGINDATE" => "Дата начала сделки",
        "ASSIGNED_BY_ID" => "Идентификатор ответственного за сделку",
        "CREATED_BY_ID" => "Идентификатор создателя сделки",
        "MODIFY_BY_ID" => "Идентификатор пользователя, последний раз изменившего сделку",
        "DATE_CREATE" => "Дата создания сделки",
        "DATE_MODIFY" => "Дата последнего изменения сделки",
        "COMPANY_ID" => "Идентификатор компании, связанной с сделкой",
        "CONTACT_ID" => "Идентификатор контакта, связанного с сделкой",
        "CATEGORY_ID" => "Идентификатор категории сделки",
        "UF_" => "Значения пользовательских полей сделки",
    ),
    "db_leads" => array(
        "ID" => "Идентификатор лидa",
        "TITLE" => "Название лидa",
        "NAME" => "Имя контакта, связанного с лидом",
        "LAST_NAME" => "Фамилия контакта, связанного с лидом",
        "SECOND_NAME" => "Отчество контакта, связанного с лидом",
        "COMPANY_TITLE" => "Название компании, связанной с лидом",
        "SOURCE_ID" => "Идентификатор источника лида",
        "SOURCE_DESCRIPTION" => "Описание источника лида",
        "STATUS_ID" => "Идентификатор статуса лида",
        "OPPORTUNITY" => "Возможная сумма сделки, связанной с лидом",
        "CURRENCY_ID" => "Идентификатор валюты возможной суммы",
        "ASSIGNED_BY_ID" => "Идентификатор ответственного за лид",
        "CREATED_BY_ID" => "Идентификатор создателя лидa",
        "MODIFY_BY_ID" => "Идентификатор пользователя, последний раз изменившего лид",
        "DATE_CREATE" => "Дата создания лидa",
        "DATE_MODIFY" => "Дата последнего изменения лидa",
        "COMMENTS" => "Комментарии к лиду",
        "UF_" => "Значения пользовательских полей лидa",
    ),
    "db_calls" => array(
        "ACCOUNT_ID" => "Идентификатор учетной записи Voximplant",
        "APPLICATION_ID" => "Идентификатор приложения Voximplant",
        "APPLICATION_NAME" => "Название приложения Voximplant",
        "INCOMING" => "Статистика входящих звонков",
        "OUTGOING" => "Статистика исходящих звонков",
        "MISSED" => "Статистика пропущенных звонков",
        "REJECTED" => "Статистика отклоненных звонков",
        "ABANDONED" => "Статистика звонков, прерванных клиентом",
        "WAITING_DURATION" => "Среднее время ожидания ответа оператора",
        "TALK_DURATION" => "Среднее время разговора оператора с клиентом",
        "HOLD_DURATION" => "Среднее время удержания оператором клиента на удержании",
        "SESSION_DURATION" => "Среднее время, проведенное оператором с клиентом в рамках одной сессии",
        "FIRST_ANSWER_DURATION" => "Среднее время, затраченное на ответ оператора на первый звонок",
        "TOTAL_USERS" => "Общее количество операторов, связанных с учетной записью Voximplant",
        "ONLINE_USERS" => "Количество операторов, находящихся в онлайн-режиме на момент запроса статистики",
        "WAITING_USERS" => "Количество операторов, находящихся в режиме ожидания звонков на момент запроса статистики",

    ),
    "db_invoice" => array(
        "ID" => "Идентификатор счёта",
        "ACCOUNT_NUMBER" => "Номер счёта",
        "ORDER_TOPIC" => "Тема счёта",
        "STATUS_ID" => "Идентификатор статуса счёта",
        "STATUS_BY" => "Информация о статусе счёта",
        "DATE_INSERT" => "Дата создания счёта",
        "DATE_BILL" => "Дата выставления счёта",
        "DATE_PAY_BEFORE" => "Дата оплаты счёта",
        "SUM" => "Сумма счёта",
        "CURRENCY" => "Валюта счёта",
        "RESPONSIBLE_ID" => "Идентификатор ответственного за счёт пользователя",
        "UF_" => "Значения пользовательских полей",
        ),
    "db_smart_process_type" => array(
        "ID" => "Идентификатор типа",
        "NAME" => "Название типа",
        "ENTITY_TYPE_ID" => "Идентификатор сущности",
        "SORT" => "Порядковый номер типа в списке типов",
        "SEMANTICS" => "Тип значений, которые могут быть связаны со сущностью",
        "DESCRIPTION" => "Описание типа",
        "IS_EDITABLE" => "Флаг, указывающий, можно ли редактировать тип",
        "IS_DELETABLE" => "Флаг, указывающий, можно ли удалять тип",
        "IS_RESTorable" => "Флаг, указывающий, можно ли восстанавливать тип",
    ),
    "db_smart_process_category" => array(
    ),
    "db_smart_process" => array(
        "ID" => "Идентификатор смарт-процесса",
        "NAME" => "Название смарт-процесса",
        "MODULE_ID" => "Идентификатор модуля, к которому относится смарт-процесс",
        "ENTITY" => "Сущность, с которой связан смарт-процесс",
        "DOCUMENT_TYPE" => "Тип документа, с которым связан смарт-процесс",
        "AUTO_EXECUTE" => "Флаг, указывающий, автоматически ли запускается смарт-процесс",
        "MODIFIED" => "Дата последнего изменения смарт-процесса",
        "TEMPLATE_ID" => "Идентификатор шаблона смарт-процесса",
        "PARAMETERS" => "Параметры смарт-процесса",
    ),
    "db_offers" => array(
        "ID" => "Идентификатор товара",
        "NAME" => "Название товара",
        "ACTIVE" => "Флаг, указывающий, активен ли товар",
        "DESCRIPTION" => "Описание товара",
        "CURRENCY_ID" => "Идентификатор валюты, в которой указана цена товара",
        "PRICE" => "Цена товара",
        "MEASURE" => "Единица измерения товара",
        "VAT_ID" => "Идентификатор ставки НДС для товара",
        "VAT_INCLUDED" => "Флаг, указывающий, включен ли НДС в цену товара",
        "SORT" => "Порядковый номер товара в списке товаров",
        "SECTION_ID" => "Идентификатор раздела, к которому относится товар",
        "PREVIEW_PICTURE" => "Идентификатор картинки товара для предпросмотра",
        "DETAIL_PICTURE" => "Идентификатор картинки товара для детального просмотра",
        "PROPERTY_" => "Значения пользовательских свойств товара",
    ),
    "db_activity" => array(
        "ID" => "Идентификатор задачи",
        "TITLE" => "Название задачи",
        "DESCRIPTION" => "Описание задачи",
        "DEADLINE" => "Крайний срок выполнения задачи",
        "START_DATE_PLAN" => "Планируемая дата начала задачи",
        "END_DATE_PLAN" => "Планируемая дата окончания задачи",
        "CREATED_DATE" => "Дата создания задачи",
        "CHANGED_DATE" => "Дата последнего изменения задачи",
        "STATUS" => "Статус задачи",
        "RESPONSIBLE_ID" => "Идентификатор ответственного за выполнение задачи пользователя",
        "CREATED_BY" => "Идентификатор пользователя, создавшего задачу",
        "GROUP_ID" => "Идентификатор группы, в которой находится задача",
        "ALLOW_CHANGE_DEADLINE" => "Флаг, указывающий, можно ли изменять крайний срок выполнения задачи",
        "ALLOW_TIME_TRACKING" => "Флаг, указывающий, включено ли учёт времени для задачи",
        "TIME_SPENT_IN_LOGS" => "Количество затраченного времени на задачу",
    ),
    "db_catalog" => array(
        "ID" => "Идентификатор каталога",
        "NAME" => "Название каталога",
        "DESCRIPTION" => "Описание каталога",
        "OWNER_ID" => "Идентификатор владельца каталога",
        "OWNER_TYPE" => "Тип владельца каталога",
        "PRODUCT_IBLOCK_ID" => "Идентификатор инфоблока, связанного с каталогом",
        "SKU_PROPERTY_ID" => "Идентификатор свойства торговых предложений",
        "VAT_ID" => "Идентификатор ставки НДС по умолчанию для товаров в каталоге",
        "VAT_INCLUDED" => "Флаг, указывающий, включен ли НДС в цену товаров по умолчанию",
        "SECTION" => "Разделы каталога",
    ),
    "db_catalog_type" => array(
        "ID" => "Идентификатор каталога",
        "NAME" => "Название каталога",
        "DESCRIPTION" => "Описание каталога",
        "OWNER_ID" => "Идентификатор владельца каталога",
        "OWNER_TYPE" => "Тип владельца каталога",
        "PRODUCT_IBLOCK_ID" => "Идентификатор инфоблока, связанного с каталогом",
        "SKU_PROPERTY_ID" => "Идентификатор свойства торговых предложений",
        "VAT_ID" => "Идентификатор ставки НДС по умолчанию для товаров в каталоге",
        "VAT_INCLUDED" => "Флаг, указывающий, включен ли НДС в цену товаров по умолчанию",
        "SECTION" => "Разделы каталога",
    ),
    "db_product" => array(
        "ID" => "Идентификатор товара",
        "NAME" => "Название товара",
        "ACTIVE" => "Флаг, указывающий, активен ли товар",
        "DESCRIPTION" => "Описание товара",
        "CURRENCY_ID" => "Идентификатор валюты, в которой указана цена товара",
        "PRICE" => "Цена товара",
        "MEASURE" => "Единица измерения товара",
        "VAT_ID" => "Идентификатор ставки НДС для товара",
        "VAT_INCLUDED" => "Флаг, указывающий, включен ли НДС в цену товара",
        "SORT" => "Порядковый номер товара в списке товаров",
        "SECTION_ID" => "Идентификатор раздела, к которому относится товар",
        "PREVIEW_PICTURE" => "Идентификатор картинки товара для предпросмотра",
        "DETAIL_PICTURE" => "Идентификатор картинки товара для детального просмотра",
        "PROPERTY_" => "Значения пользовательских свойств товара",
    ),
    "db_comments" => array(
        "ID" => "Идентификатор комментария",
        "ENTITY_ID" => "Идентификатор сущности (например, сделки, контакта и т.д.), к которой относится комментарий",
        "ENTITY_TYPE_ID" => "Идентификатор типа сущности",
        "COMMENT" => "Текст комментария",
        "FILES" => "Прикрепленные к комментарию файлы",
        "AUTHOR_ID" => "Идентификатор пользователя, оставившего комментарий",
        "CREATED" => "Дата и время создания комментария",
        "MODIFIED" => "Дата и время последнего изменения комментария",
    ),
    "db_work_time" => array(
        "ID" => "идентификатор записи отчета",
        "USER_ID" => "идентификатор пользователя, для которого получен отчет",
        "USER_NAME" => "имя пользователя",
        "USER_LAST_NAME" => "фамилия пользователя",
        "USER_SECOND_NAME" => "отчество пользователя",
        "USER_LOGIN" => "логин пользователя в Битрикс24",
        "USER_PERSONAL_GENDER" => "пол пользователя",
        "DATE_START" => "дата начала периода, за который запрашивается отчет",
        "DATE_FINISH" => "дата окончания периода, за который запрашивается отчет",
        "TIME_START" => "время начала отчетного периода",
        "TIME_FINISH" => "время окончания отчетного периода",
        "DURATION" => "продолжительность рабочего времени в секундах",
        "TASKS_COUNT" => "количество задач, выполненных за отчетный период",
        "TASKS_TIME" => "время, затраченное на выполнение задач, в секундах",
        "EVENTS_COUNT" => "количество событий, связанных с рабочим временем, за отчетный период",
        "EVENTS_TIME" => "время, затраченное на события, связанные с рабочим временем, в секундах",
    ),
);